default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Lecuong2001@
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_project_development

test:
  <<: *default
  database: rails_project_test

production:
  <<: *default
  database: rails_project_production
  username: rails_project
  password: <%= ENV['RAILS_PROJECT_DATABASE_PASSWORD'] %>
